//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOSP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasketGame
    {
        public int ID { get; set; }
        public int BasketID { get; set; }
        public int GameID { get; set; }
        public bool isPaid { get; set; }
    
        public virtual Basket Basket { get; set; }
        public virtual Game Game { get; set; }
    }
}
