//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOSP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kutuphane
    {
        public int KutuphaneID { get; set; }
        public int KullaniciID { get; set; }
        public int OyunID { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
        public virtual Oyun Oyun { get; set; }
    }
}
