//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOSP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oyun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Oyun()
        {
            this.Kutuphanes = new HashSet<Kutuphane>();
            this.Rapors = new HashSet<Rapor>();
            this.sepetOyuns = new HashSet<sepetOyun>();
        }
    
        public int OyunID { get; set; }
        public string OyunAdi { get; set; }
        public int OyunFiyati { get; set; }
        public string OyunAciklama { get; set; }
        public int YapimciID { get; set; }
        public int KategoriID { get; set; }
        public DateTime CikisTarihi { get; set; }
    
        public virtual Kategori Kategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kutuphane> Kutuphanes { get; set; }
        public virtual Yapimci Yapimci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rapor> Rapors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sepetOyun> sepetOyuns { get; set; }
    }
}
