//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOSP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sepetOyun
    {
        public int ID { get; set; }
        public int SepetID { get; set; }
        public int OyunID { get; set; }
        public bool odendi { get; set; }
    
        public virtual Oyun Oyun { get; set; }
        public virtual Sepet Sepet { get; set; }
    }
}
