//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOSP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DOSPEntities : DbContext
    {
        public DOSPEntities()
            : base("name=DOSPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adminRapor> adminRapors { get; set; }
        public virtual DbSet<adminTicket> adminTickets { get; set; }
        public virtual DbSet<Kategori> Kategoris { get; set; }
        public virtual DbSet<Kullanici> Kullanicis { get; set; }
        public virtual DbSet<Kutuphane> Kutuphanes { get; set; }
        public virtual DbSet<Oyun> Oyuns { get; set; }
        public virtual DbSet<Rapor> Rapors { get; set; }
        public virtual DbSet<RaporKategori> RaporKategoris { get; set; }
        public virtual DbSet<Sepet> Sepets { get; set; }
        public virtual DbSet<sepetOyun> sepetOyuns { get; set; }
        public virtual DbSet<Table> Tables { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
        public virtual DbSet<Yapimci> Yapimcis { get; set; }
    }
}
